### ISSUE TITLE
Have you seen amd hipify?

### ISSUE THREAD

**Issue by bhack** [hughperkins/cuda-on-cl#1]
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/clang-hipify/README.md

**Comment by hughperkins** [comment]
Not sure your "issue" is really an issue as such => closing.  As far as your question, can you confirm which opencl platforms / versions are supported by hipify?

**Comment by bhack** [comment]
It is noto a bug. It is just to point you to a "similar" project. Hip actually support only nvcc and hcc compilers.

**Comment by hughperkins** [comment]
Ok.  Good info.  Thanks! :-)

**Comment by bhack** [comment]
Nvcc it is Nvidia :) If you want the list of hcc Target Platfoms see the relative section in http://gpuopen.com/compute-product/hcc-heterogeneous-compute-compiler/

**Comment by hughperkins** [comment]
Yes.  Seems it doesnt really support OpenCL?

**Comment by bhack** [comment]
It is not opencl.. See FAQ and Terminolgy section of https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/README.md

**Comment by hughperkins** [comment]
Ok.  To what extent is hipify supported on Intel GPUs and mobile GPUs?

**Comment by bhack** [comment]
It is not about hipify it is about hcc.
HCC supports OpenMP 3.1 on CPU. The support for OpenMP 4.x accelerator offloading is currently in development.

**Comment by bhack** [comment]
See actually available compiler backends https://github.com/RadeonOpenCompute/hcc/wiki
