### ISSUE TITLE
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean       '-Wno-uninitialized'? [-Wunknown-warning-option]

### ISSUE THREAD

**Issue by iame6162013** [hughperkins/cuda-on-cl#19]
During cocl compilation a warning will crop up, this warning is 'easilly' prevented by adding 

> LLVM_COMPILE_FLAGS=${LLVM_COMPILE_FLAGS//-Wno-maybe-uninitialized/}

before line 337 in /bin/cocl .

The warning in question:

> warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]

**Comment by iame6162013** [comment]
It's a work around for this big https://bugs.llvm.org//show_bug.cgi?id=24979

**Comment by hughperkins** [comment]
Thanks!  I see you working on getting it working on arch. Cool :-) . Am I right in thinking you need to use a different version of llvm on arch?

**Comment by iame6162013** [comment]
You are correct. I'm not really experienced with llvm, so it may not work out. But I'll try!
(Oh, and if you want to know why rocm (amd), has an open source opencl implementation!)

**Comment by hughperkins** [comment]
Hi. Looks like you are using llvm-4.0, is that right?  How well is that working for you? (ie, to what extent could it be worth my considering upgrading the requirements from 3.8 to 4.0?)

**Comment by hughperkins** [comment]
Seems like, in 4.0 `PointerType` no longer sits next to `ArrayType` and so on in the inheritance diagram. It inherits directly from `Type`. This sort of makes sense, but probably implies a whole bunch of pain with migrating across... And, `getPointerElementType`seems to have either vanished, or moved around the hierarchy a bit => going to cause a bit more pain :-P . Neither are insurmountable, but might need a bit of leg-work...

**Comment by hughperkins** [comment]
(for the `CloneFunction` method, I'm not sure to what extent the change is backwards-incompatible, but we can merge it into 3.8.0 code safely, if we guard it like:

```
#if(LLVM_VERSION_MAJOR == 4)
#pragma message("llvm 4 detected")
newFunc = CloneFunction(F,
               valueMap);
#else
newFunc = CloneFunction(F,
               valueMap,
               false);
#endif
```
(or similar)

**Comment by hughperkins** [comment]
Hi. You might find this branch interesting: https://github.com/hughperkins/coriander/tree/llvm-4.0 . It at least can build `make run-cuda_sample`, using llvm 4.0 :-)

**Comment by hughperkins** [comment]
Added a couple more commits, that allow the tensorflow file `xent_op_gpu.cc` to compile, which is a fairly random file, but I was encountering a weird issue on it, in llvm-3.8, so decided to see what happens in 4.0. Well, the issue is unchanged :-P . Anyway, it is a fairly representative tensorflow file, and it compiles now, with the proviso that one uses the cutting-edge version of Eigen, ie the one in `default` branch, of the eigen mercurial, https://bitbucket.org/eigen/eigen/commits/branch/default . I tested when the 25th april commit 2b969e5 was `tip`.

**Comment by iame6162013** [comment]
Thank you!

This should hopefully help me to look in the right direction when trying to port it to llvm-4.0 . :)

**Comment by hughperkins** [comment]
tensorflow runs on llvm 4.0 ok now.

**Comment by hughperkins** [comment]
(oh, hmmm, might still be some stuff missing)

**Comment by hughperkins** [comment]
(well, as well-ish as on llvm-3.8. there are still some kernels missing, eg for random numbers, and a coupel of others)
