### ISSUE TITLE
Translate CUDA directly to SPIR omitting OpenCL code

### ISSUE THREAD

**Issue by inferrna** [hughperkins/cuda-on-cl#2]
1. There is a tool to produce LLVM IR from CUDA source https://developer.nvidia.com/cuda-llvm-compiler
2. And a tool to convert LLVM IR -> SPIR https://github.com/KhronosGroup/SPIRV-LLVM

Why not to use this combo? (I would try it by myself, but I think you may did it already.)

**Comment by hughperkins** [comment]
Yes, if you have a SPIR-enabled GPU, no need to convert into OpenCL.

**Comment by inferrna** [comment]
But it seems to be translated into OpenCL
```
$ ./test/cuda_sample
Using Advanced Micro Devices, Inc. , OpenCL platform: AMD Accelerated Parallel Processing
Using OpenCL device: Pitcairn
__internal__ build log: 
"/tmp/OCL7436T1.cl", line 9: warning: goto statement may cause irreducible
          control flow
          goto v4;
          ^

"/tmp/OCL7436T1.cl", line 11: warning: goto statement may cause irreducible

$ ldd ./test/cuda_sample
	linux-vdso.so.1 =>  (0x00007ffe397cb000)
	libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f3b22011000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3b21c89000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3b21a71000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3b216a1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3b21499000)
	/lib64/ld-linux-x86-64.so.2 (0x00005618013ca000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3b21189000)
```
I'm on latest AMD Crimson for linux (one-year old Crimson 15.12 )

**Comment by hughperkins** [comment]
I dont understand your question.  Do you mean, on AMD devices, why dont I skip the opencl-generation step?  Simply because I'm creating a very general library, that should ideally work on all opencl 1.2-enabled devices.  I might add an option to feed the IR directly into cards that accept it.

By the way, do you know that SPIR-V is essentialy just llvm IR?  I'm not sure exactly what the 'SP' bit stands for,  'standardized'? but SPIR-V is basically just standardized IR.

**Comment by inferrna** [comment]
AND OpenCL itself is just standardized C, but with some limitations compare to CUDA (forbid to use ```__global ** dtype``` for example). If we use SPIR those limitations can be easy omitted (seems more easily than on OpenCL-source level)

**Comment by bhack** [comment]
Differences to LLVM IR
● Can be translated to another IR with a very small self 
contained translator
● Binary format is a simple linear stream of words which 
can be decoded with a very small decoder
● Native support for matrices and unsigned integers
● Special built-in variables and many graphics idioms are 
native to SPIR-V
● No metadata needed to support the features of GLSL

**Comment by hughperkins** [comment]
Well, address spaces are certainly a total pain, in cuda -> opencl.  Imagine the following function:
```
__device__ void addfive(float *data) {
    data[0] += 5.0f;
}
```
In OpenCL, should it be:
```
void _Z7addfivePf(float* data) {
    label0:;
    float v1 = data[0];
    float v2 = v1 + 5.0f;
    data[0] = v2;
    return;
}
```
or:
```
void _Z7addfivePf(global float* data) {
    label0:;
    float v1 = data[0];
    float v2 = v1 + 5.0f;
    data[0] = v2;
    return;
}
```
?  So we probalby need to create both? just with different names, like `Z7addfivePf_priv` and `Z7addfivePf_glob`.

But, if we have several pointer arguments, we will need combinatorially many of these :-P

**Comment by hughperkins** [comment]
Question: how well supported is SPIR-V on different devices?  Personally, I have access to the following devices:
- NVIDIA 940M
- NVIDIA K520
- NVIDIA Titan X
- Intel HD5500

Mostly I'm testing on the Intel, since it's the only non-nvidia gpu I have access to :-P

**Comment by bhack** [comment]
I think that in Opencl 2.1 and Vulkan it is mandatory.

**Comment by bhack** [comment]
"An application that uses a valid SPIR IR instance should be runnable on any OpenCL platform supporting the cl_khr_spir extension and the matching SPIR version. (A single platform/device combination could support more than one version of SPIR IR; see the CL_DEVICE_SPIR_VERSIONS device query.) The SPIR IR instance could have been generated by any tool, provided it is valid SPIR IR."

**Comment by hughperkins** [comment]
Yes, but 2.1 is like, years away :-P  eg take some mobile gpus, https://en.wikipedia.org/wiki/Mali_(GPU)  Even the latest one is only 2.0.  And most people are not using the very latest gpu.

- NVIDIA is on 1.2
- beignet is on 1.2

**Comment by bhack** [comment]
You can use clGetDeviceInfo call and query for CL_DEVICE_IL_VERSION

**Comment by bhack** [comment]
I don't know closed source plan for Nvidia but for opensoruce https://phabricator.pmoreau.org/w/mesa/opencl_through_spirv_current_status/.
Rember that Vulkan could push SPIR-V with more pressure that Opencl

**Comment by hughperkins** [comment]
youre avoiding the question :-P  Pick some random consumer devices, that people are actually using, today, and for each one indicate whether they support SPIR-V.  I'll start the list of devices:
- 940M
- Intel HD5500  (obviously I'm biased by actually having these two gpus, in my laptop, but hey, its my project :-P)
- Adreno 330 (what I have, again.  Hmmm, its actually on 1.1 :-P  But I'm sure I could hack around to get 1.1 working, or just upgrade my phone... to some 1.2 gpu perhaps)
- Mali gpu T880
- ...add more examples here...

**Comment by hughperkins** [comment]
> Rember that Vulkan could push SPIR-V with more pressure that Opencl

You have to pick your battles.  My own battle right now is to get Tensorflow working, in OpenCL, today, with devices that people have.

:)

**Comment by bhack** [comment]
What I mean is that on most of all this devices probably you can already ingest SPIR-V through Vulkan driver cause the game industry has a major pushing force than Opencl. I don't know how much having a Vulkan driver could potentially speedup the Opencl side.

**Comment by bhack** [comment]
I.e. Andreno SDK Vulkan https://developer.qualcomm.com/software/adreno-gpu-sdk

**Comment by bhack** [comment]
Or http://malideveloper.arm.com/downloads/deved/tutorial/SDK/Vulkan/1.0/buildingTheSamples.html#buildingSPIRVShaders

**Comment by inferrna** [comment]
> Well, address spaces are certainly a total pain, in cuda -> opencl. Imagine the following function:

Yes, but how the CUDA compiler solves it? CUDA also support many types of memory that seems to be hidden in this simple declaration
```__device__ void addfive(float *data)```
it very possible that somewhere on IR level of CUDA compiler we can see the solution (or on binary level, that also possible)

**Comment by hughperkins** [comment]
There is a diagram of how cuda-on-cl works.  The steps are:
- convert cu file to ll files.  These contain IR
- convert the device side ll file into OpenCL
- (some other steps for hostside)

The device side IR is available for inspection.  You can look for the file called '(something)-device.ll'.  There is no information on function parameter address spaces.  At least: I dont see any.  I assume that the CUDA driver handles this at runtime.

**Comment by hughperkins** [comment]
There's a diagram of how cuda-on-cl works. The steps are:
- convert cu file to ll files. These contain ir
- convert the device side ll file into opencl
- (some other steps for hostside)

The device side ir is available for inspection. You can look for the file called 'something-device.ll'. there is no information on function parameter address spaces. I assume that the cuda driver handles this at runtime.



On 21 October 2016 11:31:04 BST, inferrna <notifications@github.com> wrote:
>> Well, address spaces are certainly a total pain, in cuda -> opencl.
>Imagine the following function:
>
>Yes, but how the CUDA compiler solves it? CUDA also support many types
>of memory that seems to be hidden in this simple declaration
>```__device__ void addfive(float *data)```
>it very possible that somewhere on IR level of CUDA compiler we can see
>the solution (or on binary level, that also possible)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/cuda-on-cl/issues/2#issuecomment-255348425

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hughperkins** [comment]
Hi guys, so I have a Mac now, with a Radeon Pro 450.  I did `brew install clinfo`, and then `clinfo`, and output for the Radeon is:
```
cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_depth_images cl_APPLE_command_queue_priority cl_APPLE_command_queue_select_compute_units cl_khr_fp64
```
This means it wont accept any kind of SPIR, is that right? Or should I be looking at some other place, or using a different driver? (full output here: https://gist.github.com/hughperkins/48bb9f79358951fedfd3de648bdb2897 )
