### ISSUE TITLE
what's the relationship of this cool repos?

### ISSUE THREAD

**Issue by alephman** [hughperkins/cuda-on-cl#4]
Hi hughperkins,
Could you help me understand  the relationship of your cool repos:  CLBlast,  EasyCL, DeepCL,cuda-on-cl ? 
thanks!

**Comment by hughperkins** [comment]
Sure:
- DeepCL  A convolutional neural network, built from the ground-up, 100% OpenCL
   - people appreciate it for:
      - the convenient commandline syntax for expressing networks like `32c5-mp2-32c5-mp2-50n-10n`,
      - and for the ability to run on Windows (it runs on all three major platforms actually: windows, linux, Mac)
      - it was the first OpenCL library to appear on Soumith's [convnet-benchmarks](https://github.com/soumith/convnet-benchmarks) page
- CLBlast is not mine.  It's [Cedric Nugteren's](https://github.com/CNugteren).  It's a BLAS implementation for OpenCL.  BLAS handles primarily matrix multiplication, also matrix-vector multiplication
- EasyCL is a low-level middleware that makes launching kernels from C++ a lot less painful than the low-level OpenCL API.  I think there is a C++ API for OpenCL too actually, but I think EasyCL adds a few more bells and whistles, and plus I've been using it for a while now, across all my projects, seems to do what I need :-)
- cuda-on-cl lets you build NVIDIA® CUDA™ applications for use on OpenCL devices.

You missed one by the way ;-)  Actually two:
- https://github.com/hughperkins/distro-cl port of [Torch](https://torch.ch) library to OpenCL
- https://github.com/hughperkins/jeigen  Java wrappers for the [Eigen](http://eigen.tuxfamily.org) library, which is the same library underlying Tensorflow.  Eigen handles tensor operations, like addition, reduction, sort, and so on.

**Comment by alephman** [comment]
Thanks a lot hughperkins!  I still have 2 questions:
 1. Does  the Eigen support OpenCL?
2.  Why tensorflow use  Eigen instead of  BLAS?

**Comment by hughperkins** [comment]
> Does the Eigen support OpenCL?

Not out-of-the-box.  But it does build into OpenCL, if you use cuda-on-cl.  But that's because Eigen supports CUDA, and cuda-on-cl can compile CUDA applications into OpenCL.

> Why tensorflow use Eigen instead of BLAS?

Tensorflow uses Eigen and BLAS
- BLAS is highly optimized for matrix multiplication
- doesnt handle things like: reduction, sorting, per-element addition etc
