### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by dcolley** [hughperkins/cuda-on-cl#5]
Hi Hugh,
Could you please have a look at this one?
https://github.com/hughperkins/tensorflow-cl/issues/2

I can remove it from the tensorflow-cl repo and paste it all here if you prefer.

**Comment by hughperkins** [comment]
lets keep tensorflow issues in the tensorflow-cl repo
=> closing this one

**Comment by imsrgadich** [comment]
Hi @dcolley / @hughperkins, can you please help me with this #81? Thank you. 

https://github.com/hughperkins/coriander/issues/81
