### ISSUE TITLE
compiling error on x86

### ISSUE THREAD

**Issue by alephman** [hughperkins/cuda-on-cl#7]
recently I re-install my laptop(x86_64), following readme to compile the cuda-on-cl, but get the error like this:   http://pastebin.ubuntu.com/23475742/. 
The same situation in Docker, I am not sure why.

**Comment by hughperkins** [comment]
Good point!  Thanks for the heads-up.  Should be working now?  (You'll need to do `git submodule update --init`, after doing `git pull`)

**Comment by hughperkins** [comment]
oh wiat, still something missing.  checking...

**Comment by hughperkins** [comment]
Should be mildly healthier now?

**Comment by hughperkins** [comment]
Big heads-up though.  Curently I'm hard at work on a *massive* overhaul ,in branch `runtime-compile`, https://github.com/hughperkins/cuda-on-cl/compare/runtime-compile?expand=1  It's mildly broken, but I can compile/run cuda_sample.cu ok.  I think that since you're working on trying to get basic things working for now, might be good to try this branch?

quick heads-up: the main changes in this branch are:
- major refactorization, you probably wont notice this too much
- generation of device-side opencl from device-side IR happens at runtime now => you wil lalmost certainly notice this change.  Whether this makes things work better or worse for you is uncertain to me at this time.

**Comment by alephman** [comment]
after checking out  runtime-compile branch, re-compile again, get another error http://pastebin.ubuntu.com/23478287/

**Comment by hughperkins** [comment]
Hmmm, builds ok for me.  And I tried in docker earlier too. And worked in docker too.  Are you sure you're trying 'runtime-compile' branch?  If I switch to runtime-compile branch, there is no 'ConstantDumper.cpp' file at all in fact:
```
(env3cl) ubuntu@peach:~/git/cuda-on-cl/build$ git checkout runtime-compile 
Already on 'runtime-compile'
Your branch is up-to-date with 'hugh/runtime-compile'.
(env3cl) ubuntu@peach:~/git/cuda-on-cl/build$ ls ../src/Constant*
ls: cannot access '../src/Constant*': No such file or directory
(env3cl) ubuntu@peach:~/git/cuda-on-cl/build$ git checkout instruction-own-class 
Switched to branch 'instruction-own-class'
Your branch is up-to-date with 'hugh/instruction-own-class'.
(env3cl) ubuntu@peach:~/git/cuda-on-cl/build$ ls ../src/Constant*../src/ConstantDumper.cpp  ../src/ConstantDumper.h
```
Can you do:
```
git status
git log -n 3
```
... and paste the results?

**Comment by alephman** [comment]
Thanks hughperkins ,  git clone the whole repo again  and checkout runtime-compile  branch, it works now. Recently the github is very very slow in my side, probably it broke somewhere.
BTW, comment out  -device.cl in  cocl.Makefile?

**Comment by hughperkins** [comment]
Yes, opencl generation is done at runtime now, from hostside_opencl_funcs.cpp

Ir-to-opencl is still available, but just for debugging/testing really.


On 15 November 2016 03:35:41 GMT+00:00, alephman <notifications@github.com> wrote:
>Thanks hughperkins ,  git clone the whole repo again  and checkout
>runtime-compile  branch, it works now. Recently the github is very very
>slow in my side, probably it broke somewhere.
>BTW, comment out  -device.cl in  cocl.Makefile?
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/hughperkins/cuda-on-cl/issues/7#issuecomment-260538389

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hughperkins** [comment]
(oh, hmmm, note my observation "it works ok from docker" was actually running the clone, inside the docker, from master branch, hence ignore that comment :-) )

**Comment by hughperkins** [comment]
(but note that the technology exists now to build other branches :-) https://github.com/hughperkins/cuda-on-cl/blob/runtime-compile/docker/Dockerfile#L3 )

**Comment by hughperkins** [comment]
Note that massive overhaul/merge-to-master might mean that some things that were broken for work better/differently now?

**Comment by hughperkins** [comment]
this seems relally old, and non-specific. Lets close it. Please open new issues for any outstanding issues that havent been addressed here.
